name: "Pull requests"

on:
  pull_request:
    paths:
      - "components/**"
      - "terragrunt/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 0.13.5
  TERRAGRUNT_VERSION: v0.26.0
  TF_VAR_rds_cluster_password: ${{ secrets.RDS_CLUSTER_PASSWORD }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "bin" >> $GITHUB_PATH

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Get touched Terragrunt modules
        run: |
          MODULES=`echo '${{ steps.changed-files.outputs.all }}' | jq -c '[.[] | match("(.*components?)\/(.*)\/").captures[1].string] | unique | select(length > 0)'`
          echo "MODULES=$MODULES" >> $GITHUB_ENV

      - name: Get touched Terragrunt configurations
        run: |
          CONFIGS=`echo '${{ steps.changed-files.outputs.all }}' | jq -c '[.[] | match("(.*terragrunt?)\/(.*)\/").captures[1].string] | unique | select(length > 0)'`
          echo "CONFIGS=$CONFIGS" >> $GITHUB_ENV

      - name: Apply website-cms
        if: contains(env.MODULES, 'website-cms') || contains(env.CONFIGS, 'website-cms')
        run: |
          cd terragrunt/website-cms
          ../../bin/terragrunt plan --terragrunt-non-interactive

