name: "Pull requests"

on:
  pull_request:
    paths:
      - "components/**"
      - "terragrunt/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.0.3
  TERRAGRUNT_VERSION: 0.31.1
  TF_VAR_rds_cluster_password: ${{ secrets.RDS_CLUSTER_PASSWORD }}
  TF_VAR_asset_bucket_name: ${{ secrets.ASSET_BUCKET_NAME }}
  TF_VAR_strapi_aws_access_key_id: ${{ secrets.STRAPI_AWS_ACCESS_KEY_ID }}
  TF_VAR_strapi_aws_secret_access_key: ${{ secrets.STRAPI_AWS_SECRET_ACCESS_KEY }}
  TF_VAR_github_token: ${{ secrets.TOKEN }}
  TF_INPUT: false

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            common:
              - '.github/workflows/pull_requests.yml'
              - 'terragrunt/terragrunt.hcl'
            website-cms:
              - 'components/website-cms/**'
              - 'terragrunt/website-cms/**'

      - name: Terragrunt plan website-cms
        if: steps.filter.outputs.website-cms == 'true' || steps.filter.outputs.common == 'true'
        uses: cds-snc/terraform-plan@v2
        with:
          directory: "terragrunt/website-cms"
          comment-delete: "true"
          comment-title: "Website CMS"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
